#!/usr/bin/env python

# Author: JIN Xiaoyang
# Date  : 2016-07-18

# Filter two fastq.gz files generated by `fastq-dump` (add --gzip and
# --split-files paraments), separate paired and unpaired reads

# Run the following command to get the test set:
## fastq-dump --gzip --split-files -N 28181762 -X 28181782 SRR1554534

def filter_fastq(infile_handle_1, infile_handle_2,
        output_1='', output_2='', output_s=''):
    output_1 = gzip.open(output_1, 'wb')
    output_2 = gzip.open(output_2, 'wb')
    output_s = gzip.open(output_s, 'wb')

    line_1 = infile_handle_1.readline()
    line_2 = infile_handle_2.readline()

    while line_1 and line_2:
        id_1 = int(line_1.split()[1])
        id_2 = int(line_2.split()[1])

        if id_1 < id_2:
            output_s.write(line_1)
            [output_s.write(infile_handle_1.readline()) for x in range(3)]
            line_1 = infile_handle_1.readline()

        elif id_1 > id_2:
            output_s.write(line_2)
            [output_s.write(infile_handle_2.readline()) for x in range(3)]
            line_2 = infile_handle_2.readline()

        ## paired reads
        else:
            output_1.write(line_1)
            [output_1.write(infile_handle_1.readline()) for x in range(3)]
            output_2.write(line_2)
            [output_2.write(infile_handle_2.readline()) for x in range(3)]

            line_1 = infile_handle_1.readline()
            line_2 = infile_handle_2.readline()

    while line_1:
        output_s.write(line_1)
        line_1 = infile_handle_1.readline()

    while line_2:
        output_s.write(line_2)
        line_2 = infile_handle_2.readline()

    output_1.close()
    output_2.close()
    output_s.close()

if __name__ == '__main__':
    import gzip
    import sys

    args = sys.argv[1:]
    if len(args) < 2:
        print('Usage: %s fq_1 fq_2\n\t[fq_out_1 fq_out_2 fq_unpaired]'
                % sys.argv[0])
        sys.exit()
    elif len(args) < 5:
        # default name of fastq files from `fastq-dump` is something like:
        # * SRR1554534_1.fastq.gz
        # * SRR1554534_2.fastq.gz
        output_1 = args[0][:args[0].index('.')] + '.new.fastq.gz'
        output_2 = args[1][:args[1].index('.')] + '.new.fastq.gz'
        output_s = args[0][:args[0].index('_')] + '_s.new.fastq.gz'
    else:
        output_1, output_2, output_s = args[2:5]

    input_1 = gzip.open(args[0], 'rb')
    input_2 = gzip.open(args[1], 'rb')

    filter_fastq(input_1, input_2,
            output_1, output_2, output_s)

    input_1.close()
    input_2.close()
